import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Terms of Service' }

export default function TermsPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
      <p className="text-slate-500 text-sm mb-8">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

      <Section title="1. Acceptance of Terms">
        <p>By accessing or using The Arbitrator platform ("Platform", "Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>
        <p>We reserve the right to modify these terms at any time. Continued use of the Platform after changes constitutes acceptance.</p>
      </Section>

      <Section title="2. Description of Service">
        <p>The Arbitrator is an AI-powered dispute resolution platform that allows two parties to submit arguments, evidence, and claims, while an AI system acts as a neutral mediator and arbitration assistant.</p>
        <p>The Platform is NOT:</p>
        <ul>
          <li>A law firm or legal services provider</li>
          <li>A substitute for licensed legal counsel</li>
          <li>A court of law or binding arbitration tribunal (unless both parties expressly agree)</li>
          <li>A guarantee of any specific outcome</li>
        </ul>
      </Section>

      <Section title="3. User Accounts">
        <p>You must create an account to use the Platform. You are responsible for:</p>
        <ul>
          <li>Maintaining the confidentiality of your credentials</li>
          <li>All activity that occurs under your account</li>
          <li>Providing accurate and current information</li>
          <li>Notifying us immediately of any unauthorized access</li>
        </ul>
        <p>You must be at least 18 years of age to use the Platform.</p>
      </Section>

      <Section title="4. Acceptable Use">
        <p>You agree not to:</p>
        <ul>
          <li>Submit false, fraudulent, or misleading information</li>
          <li>Use the Platform for harassment, abuse, or illegal purposes</li>
          <li>Attempt to manipulate the AI system through deceptive prompts</li>
          <li>Upload malicious files or content</li>
          <li>Violate any applicable laws or regulations</li>
          <li>Infringe the intellectual property rights of any third party</li>
        </ul>
        <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>
      </Section>

      <Section title="5. Subscription and Billing">
        <p>The Platform offers free and paid subscription plans. By subscribing to a paid plan:</p>
        <ul>
          <li>You authorize us to charge your payment method on a recurring basis</li>
          <li>Subscriptions auto-renew unless canceled at least 24 hours before the renewal date</li>
          <li>Refunds are issued at our discretion, except where required by law</li>
          <li>Price changes will be communicated 30 days in advance</li>
        </ul>
        <p>Payments are processed by Stripe. We do not store your payment information.</p>
      </Section>

      <Section title="6. AI-Generated Content">
        <p>All AI outputs on the Platform, including neutral titles, mediation proposals, and arbitration resolutions, are:</p>
        <ul>
          <li>Advisory in nature and do not constitute legal advice</li>
          <li>Not legally binding unless both parties expressly agree in writing</li>
          <li>Based solely on the information provided by the parties</li>
          <li>Generated by automated AI systems and not reviewed by human legal professionals</li>
        </ul>
        <p>You should consult a licensed attorney before taking legal action based on any AI output.</p>
      </Section>

      <Section title="7. Privacy and Data">
        <p>Your use of the Platform is subject to our Privacy Policy. By using the Platform, you consent to the collection and use of information as described therein.</p>
        <p>We implement industry-standard security measures to protect your data, including row-level security at the database level ensuring only dispute participants can access case data.</p>
      </Section>

      <Section title="8. Intellectual Property">
        <p>The Platform, including its design, code, and AI systems, is owned by The Arbitrator and protected by intellectual property laws.</p>
        <p>You retain ownership of content you submit. By submitting content, you grant us a limited license to process it for the purpose of providing the Service.</p>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ARBITRATOR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE PLATFORM.</p>
        <p>Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.</p>
      </Section>

      <Section title="10. Governing Law">
        <p>These Terms are governed by and construed in accordance with applicable law. Any disputes shall be resolved through binding arbitration, except where prohibited by law.</p>
      </Section>

      <Section title="11. Contact">
        <p>For questions about these Terms, contact us at <a href="mailto:legal@thearbitrator.app" className="text-arbitrator-600 hover:underline">legal@thearbitrator.app</a>.</p>
      </Section>
    </article>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-xl font-semibold text-slate-900 mb-3">{title}</h2>
      <div className="text-slate-600 space-y-3 leading-relaxed text-sm">{children}</div>
    </div>
  )
}
